apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/app-Deployment.yaml
- manifests/app-play-framework-conf-ConfigMap.yaml
- manifests/app-Service.yaml
- manifests/cache-Deployment.yaml
- manifests/cache-Service.yaml
- manifests/rdb-init-sh-override-ConfigMap.yaml
- manifests/rdb-Service.yaml
- manifests/rdb-StatefulSet.yaml
- manifests/search-Deployment.yaml
- manifests/search-log4j2-properties-override-ConfigMap.yaml
- manifests/search-Service.yaml
- manifests/web-Deployment.yaml
- manifests/web-Service.yaml
