apiVersion: v1
kind: Service
metadata:
  labels:
    name: cache
  name: cache
  namespace: talkyard
spec:
  ports:
  - name: cache-cache
    port: 6379
    targetPort: 6379
  selector:
    name: cache
