apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: talkyard
    app.kubernetes.io/version: v0.2021.10-e846283fa
  name: cache
  namespace: talkyard
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: cache
  template:
    metadata:
      labels:
        name: cache
    spec:
      containers:
      - image: debiki/talkyard-cache:v0.2021.10-e846283fa
        imagePullPolicy: IfNotPresent
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 3
          tcpSocket:
            port: default
          timeoutSeconds: 5
        name: cache
        ports:
        - containerPort: 6379
          name: default
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 20
          periodSeconds: 3
          timeoutSeconds: 5
