apiVersion: v1
kind: Service
metadata:
  labels:
    name: rdb
  name: rdb
  namespace: talkyard-test
spec:
  ports:
  - name: rdb-default
    port: 5432
    targetPort: 5432
  selector:
    name: rdb
