apiVersion: v1
kind: Service
metadata:
  labels:
    name: search
  name: search
  namespace: talkyard
spec:
  ports:
  - name: search-default
    port: 9300
    targetPort: 9300
  selector:
    name: search
