apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: webserver
    app.kubernetes.io/part-of: talkyard
    app.kubernetes.io/version: v0.2021.10-e846283fa
  name: web
  namespace: talkyard
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - image: debiki/talkyard-web:v0.2021.10-e846283fa
        imagePullPolicy: IfNotPresent
        name: web
        ports:
        - containerPort: 80
          name: http
        readinessProbe:
          httpGet:
            path: /-/ping-nginx
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
