apiVersion: v1
kind: Service
metadata:
  labels:
    name: web
  name: web
  namespace: talkyard
spec:
  ports:
  - name: web-http
    port: 80
    targetPort: 80
  - name: web-https
    port: 443
    targetPort: 443
  selector:
    name: web
